{"uuid": "6036cb4a-ceff-46fe-86b8-4ceab0fb25d8", "children": ["4faf7714-d596-402a-9efe-4a0b5f4b184e"], "befores": [{"name": "_Class__pytest_setup_method", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n\n", "trace": "  File \"D:\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = next(it)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\python.py\", line 746, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\python.py\", line 661, in _call_with_optional_argument\n    func()\n  File \"E:\\python\\python_class\\Ecshop_appium\\scripts\\test_collection.py\", line 9, in setup_method\n    driver = open_app()\n  File \"E:\\python\\python_class\\Ecshop_appium\\common\\method.py\", line 22, in open_app\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"D:\\python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    proxy\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1578556930449, "stop": 1578556960215}], "start": 1578556930449, "stop": 1578556960497}